package web.app.msz.nl.backend.persistence.entities;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 *
 * Use of annotations:
 *  <p>@Entity: Marks this class as a JPA entity, which means it will be mapped to a database table.</p>
 *  <p>@Table(name = "todo"): Specifies the name of the database table to which this entity will be mapped.</p>
 *  <p>@Id: Marks the field 'id' as the primary key of the entity.</p>
 *  <p>@GeneratedValue(strategy = GenerationType.IDENTITY): Specifies that the primary key value will be automatically generated by the database.</p>
 *  <p>@Column(nullable = false): Indicates that the 'name' field cannot be null in the database, enforcing a constraint on this column.</p>
 *  <p>@Getter, @Setter: Lombok annotations that automatically generate getter and setter methods for all fields in the class, reducing boilerplate code.</p>
 *  <p>@NoArgsConstructor: Lombok annotation that generates a no-argument constructor for the class, which is required by JPA for entity instantiation.</p>
 *  <p>@AllArgsConstructor: Lombok annotation that generates a constructor with parameters for all fields in the class.</p>
 *  <p>@Builder: Lombok annotation that provides a builder pattern implementation for the class, enabling more readable and flexible object creation.</p>
 *
 */
@Entity
@Table(name = "todo")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Todo {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    private String description;

    private String tags;

    private LocalDateTime createdAt;

    private LocalDate deadlineDate;

    private boolean completed;
}
